const countryList = [
  { countryCode: "AF", countryName: "AFGHANISTAN" },
  { countryCode: "AL", countryName: "ALBANIA" },
  { countryCode: "DZ", countryName: "ALGERIA" },
  { countryCode: "AS", countryName: "AMERICAN SAMOA" },
  { countryCode: "AD", countryName: "ANDORRA" },
  { countryCode: "AO", countryName: "ANGOLA" },
  { countryCode: "AI", countryName: "ANGUILLA" },
  { countryCode: "AQ", countryName: "ANTARCTICA" },
  { countryCode: "AG", countryName: "ANTIGUA AND BARBUDA" },
  { countryCode: "AR", countryName: "ARGENTINA" },
  { countryCode: "AM", countryName: "ARMENIA" },
  { countryCode: "AW", countryName: "ARUBA" },
  { countryCode: "AU", countryName: "AUSTRALIA" },
  { countryCode: "AT", countryName: "AUSTRIA" },
  { countryCode: "AZ", countryName: "AZERBAIJAN" },
  { countryCode: "BS", countryName: "BAHAMAS" },
  { countryCode: "BH", countryName: "BAHRAIN" },
  { countryCode: "BD", countryName: "BANGLADESH" },
  { countryCode: "BB", countryName: "BARBADOS" },
  { countryCode: "BY", countryName: "BELARUS" },
  { countryCode: "BE", countryName: "BELGIUM" },
  { countryCode: "BZ", countryName: "BELIZE" },
  { countryCode: "BJ", countryName: "BENIN" },
  { countryCode: "BM", countryName: "BERMUDA" },
  { countryCode: "BT", countryName: "BHUTAN" },
  { countryCode: "BO", countryName: "BOLIVIA" },
  { countryCode: "BA", countryName: "BOSNIA AND HERZEGOVINA" },
  { countryCode: "BW", countryName: "BOTSWANA" },
  { countryCode: "BV", countryName: "BOUVET ISLAND" },
  { countryCode: "BR", countryName: "BRAZIL" },
  { countryCode: "IO", countryName: "BRITISH INDIAN OCEAN TERRITORY" },
  { countryCode: "BN", countryName: "BRUNEI DARUSSALAM" },
  { countryCode: "BG", countryName: "BULGARIA" },
  { countryCode: "BF", countryName: "BURKINA FASO" },
  { countryCode: "BI", countryName: "BURUNDI" },
  { countryCode: "KH", countryName: "CAMBODIA" },
  { countryCode: "CM", countryName: "CAMEROON" },
  { countryCode: "CA", countryName: "CANADA" },
  { countryCode: "CV", countryName: "CAPE VERDE" },
  { countryCode: "KY", countryName: "CAYMAN ISLANDS" },
  { countryCode: "CF", countryName: "CENTRAL AFRICAN REPUBLIC" },
  { countryCode: "TD", countryName: "CHAD" },
  { countryCode: "CL", countryName: "CHILE" },
  { countryCode: "CN", countryName: "CHINA" },
  { countryCode: "CX", countryName: "CHRISTMAS ISLAND" },
  { countryCode: "CC", countryName: "COCOS (KEELING) ISLANDS" },
  { countryCode: "CO", countryName: "COLOMBIA" },
  { countryCode: "KM", countryName: "COMOROS" },
  { countryCode: "CG", countryName: "CONGO" },
  { countryCode: "CD", countryName: "CONGO, THE DEMOCRATIC REPUBLIC OF THE" },
  { countryCode: "CK", countryName: "COOK ISLANDS" },
  { countryCode: "CR", countryName: "COSTA RICA" },
  { countryCode: "CI", countryName: "COTE D IVOIRE" },
  { countryCode: "HR", countryName: "CROATIA" },
  { countryCode: "CU", countryName: "CUBA" },
  { countryCode: "CY", countryName: "CYPRUS" },
  { countryCode: "CZ", countryName: "CZECH REPUBLIC" },
  { countryCode: "DK", countryName: "DENMARK" },
  { countryCode: "DJ", countryName: "DJIBOUTI" },
  { countryCode: "DM", countryName: "DOMINICA" },
  { countryCode: "DO", countryName: "DOMINICAN REPUBLIC" },
  { countryCode: "TP", countryName: "EAST TIMOR" },
  { countryCode: "EC", countryName: "ECUADOR" },
  { countryCode: "EG", countryName: "EGYPT" },
  { countryCode: "SV", countryName: "EL SALVADOR" },
  { countryCode: "GQ", countryName: "EQUATORIAL GUINEA" },
  { countryCode: "ER", countryName: "ERITREA" },
  { countryCode: "EE", countryName: "ESTONIA" },
  { countryCode: "ET", countryName: "ETHIOPIA" },
  { countryCode: "FK", countryName: "FALKLAND ISLANDS (MALVINAS)" },
  { countryCode: "FO", countryName: "FAROE ISLANDS" },
  { countryCode: "FJ", countryName: "FIJI" },
  { countryCode: "FI", countryName: "FINLAND" },
  { countryCode: "FR", countryName: "FRANCE" },
  { countryCode: "GF", countryName: "FRENCH GUIANA" },
  { countryCode: "PF", countryName: "FRENCH POLYNESIA" },
  { countryCode: "TF", countryName: "FRENCH SOUTHERN TERRITORIES" },
  { countryCode: "GA", countryName: "GABON" },
  { countryCode: "GM", countryName: "GAMBIA" },
  { countryCode: "GE", countryName: "GEORGIA" },
  { countryCode: "DE", countryName: "GERMANY" },
  { countryCode: "GH", countryName: "GHANA" },
  { countryCode: "GI", countryName: "GIBRALTAR" },
  { countryCode: "GR", countryName: "GREECE" },
  { countryCode: "GL", countryName: "GREENLAND" },
  { countryCode: "GD", countryName: "GRENADA" },
  { countryCode: "GP", countryName: "GUADELOUPE" },
  { countryCode: "GU", countryName: "GUAM" },
  { countryCode: "GT", countryName: "GUATEMALA" },
  { countryCode: "GN", countryName: "GUINEA" },
  { countryCode: "GW", countryName: "GUINEA-BISSAU" },
  { countryCode: "GY", countryName: "GUYANA" },
  { countryCode: "HT", countryName: "HAITI" },
  { countryCode: "HM", countryName: "HEARD ISLAND AND MCDONALD ISLANDS" },
  { countryCode: "VA", countryName: "HOLY SEE (VATICAN CITY STATE)" },
  { countryCode: "HN", countryName: "HONDURAS" },
  { countryCode: "HK", countryName: "HONG KONG" },
  { countryCode: "HU", countryName: "HUNGARY" },
  { countryCode: "IS", countryName: "ICELAND" },
  { countryCode: "IN", countryName: "INDIA" },
  { countryCode: "ID", countryName: "INDONESIA" },
  { countryCode: "IR", countryName: "IRAN, ISLAMIC REPUBLIC OF" },
  { countryCode: "IQ", countryName: "IRAQ" },
  { countryCode: "IE", countryName: "IRELAND" },
  { countryCode: "IL", countryName: "ISRAEL" },
  { countryCode: "IT", countryName: "ITALY" },
  { countryCode: "JM", countryName: "JAMAICA" },
  { countryCode: "JP", countryName: "JAPAN" },
  { countryCode: "JO", countryName: "JORDAN" },
  { countryCode: "KZ", countryName: "KAZAKSTAN" },
  { countryCode: "KE", countryName: "KENYA" },
  { countryCode: "KI", countryName: "KIRIBATI" },
  { countryCode: "KP", countryName: "KOREA DEMOCRATIC PEOPLES REPUBLIC OF" },
  { countryCode: "KR", countryName: "KOREA REPUBLIC OF" },
  { countryCode: "KW", countryName: "KUWAIT" },
  { countryCode: "KG", countryName: "KYRGYZSTAN" },
  { countryCode: "LA", countryName: "LAO PEOPLES DEMOCRATIC REPUBLIC" },
  { countryCode: "LV", countryName: "LATVIA" },
  { countryCode: "LB", countryName: "LEBANON" },
  { countryCode: "LS", countryName: "LESOTHO" },
  { countryCode: "LR", countryName: "LIBERIA" },
  { countryCode: "LY", countryName: "LIBYAN ARAB JAMAHIRIYA" },
  { countryCode: "LI", countryName: "LIECHTENSTEIN" },
  { countryCode: "LT", countryName: "LITHUANIA" },
  { countryCode: "LU", countryName: "LUXEMBOURG" },
  { countryCode: "MO", countryName: "MACAU" },
  {
    countryCode: "MK",
    countryName: "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF",
  },
  { countryCode: "MG", countryName: "MADAGASCAR" },
  { countryCode: "MW", countryName: "MALAWI" },
  { countryCode: "MY", countryName: "MALAYSIA" },
  { countryCode: "MV", countryName: "MALDIVES" },
  { countryCode: "ML", countryName: "MALI" },
  { countryCode: "MT", countryName: "MALTA" },
  { countryCode: "MH", countryName: "MARSHALL ISLANDS" },
  { countryCode: "MQ", countryName: "MARTINIQUE" },
  { countryCode: "MR", countryName: "MAURITANIA" },
  { countryCode: "MU", countryName: "MAURITIUS" },
  { countryCode: "YT", countryName: "MAYOTTE" },
  { countryCode: "MX", countryName: "MEXICO" },
  { countryCode: "FM", countryName: "MICRONESIA, FEDERATED STATES OF" },
  { countryCode: "MD", countryName: "MOLDOVA, REPUBLIC OF" },
  { countryCode: "MC", countryName: "MONACO" },
  { countryCode: "MN", countryName: "MONGOLIA" },
  { countryCode: "MS", countryName: "MONTSERRAT" },
  { countryCode: "MA", countryName: "MOROCCO" },
  { countryCode: "MZ", countryName: "MOZAMBIQUE" },
  { countryCode: "MM", countryName: "MYANMAR" },
  { countryCode: "NA", countryName: "NAMIBIA" },
  { countryCode: "NR", countryName: "NAURU" },
  { countryCode: "NP", countryName: "NEPAL" },
  { countryCode: "NL", countryName: "NETHERLANDS" },
  { countryCode: "AN", countryName: "NETHERLANDS ANTILLES" },
  { countryCode: "NC", countryName: "NEW CALEDONIA" },
  { countryCode: "NZ", countryName: "NEW ZEALAND" },
  { countryCode: "NI", countryName: "NICARAGUA" },
  { countryCode: "NE", countryName: "NIGER" },
  { countryCode: "NG", countryName: "NIGERIA" },
  { countryCode: "NU", countryName: "NIUE" },
  { countryCode: "NF", countryName: "NORFOLK ISLAND" },
  { countryCode: "MP", countryName: "NORTHERN MARIANA ISLANDS" },
  { countryCode: "NO", countryName: "NORWAY" },
  { countryCode: "OM", countryName: "OMAN" },
  { countryCode: "PK", countryName: "PAKISTAN" },
  { countryCode: "PW", countryName: "PALAU" },
  { countryCode: "PS", countryName: "PALESTINIAN TERRITORY, OCCUPIED" },
  { countryCode: "PA", countryName: "PANAMA" },
  { countryCode: "PG", countryName: "PAPUA NEW GUINEA" },
  { countryCode: "PY", countryName: "PARAGUAY" },
  { countryCode: "PE", countryName: "PERU" },
  { countryCode: "PH", countryName: "PHILIPPINES" },
  { countryCode: "PN", countryName: "PITCAIRN" },
  { countryCode: "PL", countryName: "POLAND" },
  { countryCode: "PT", countryName: "PORTUGAL" },
  { countryCode: "PR", countryName: "PUERTO RICO" },
  { countryCode: "QA", countryName: "QATAR" },
  { countryCode: "RE", countryName: "REUNION" },
  { countryCode: "RO", countryName: "ROMANIA" },
  { countryCode: "RU", countryName: "RUSSIAN FEDERATION" },
  { countryCode: "RW", countryName: "RWANDA" },
  { countryCode: "SH", countryName: "SAINT HELENA" },
  { countryCode: "KN", countryName: "SAINT KITTS AND NEVIS" },
  { countryCode: "LC", countryName: "SAINT LUCIA" },
  { countryCode: "PM", countryName: "SAINT PIERRE AND MIQUELON" },
  { countryCode: "VC", countryName: "SAINT VINCENT AND THE GRENADINES" },
  { countryCode: "WS", countryName: "SAMOA" },
  { countryCode: "SM", countryName: "SAN MARINO" },
  { countryCode: "ST", countryName: "SAO TOME AND PRINCIPE" },
  { countryCode: "SA", countryName: "SAUDI ARABIA" },
  { countryCode: "SN", countryName: "SENEGAL" },
  { countryCode: "SC", countryName: "SEYCHELLES" },
  { countryCode: "SL", countryName: "SIERRA LEONE" },
  { countryCode: "SG", countryName: "SINGAPORE" },
  { countryCode: "SK", countryName: "SLOVAKIA" },
  { countryCode: "SI", countryName: "SLOVENIA" },
  { countryCode: "SB", countryName: "SOLOMON ISLANDS" },
  { countryCode: "SO", countryName: "SOMALIA" },
  { countryCode: "ZA", countryName: "SOUTH AFRICA" },
  {
    countryCode: "GS",
    countryName: "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
  },
  { countryCode: "ES", countryName: "SPAIN" },
  { countryCode: "LK", countryName: "SRI LANKA" },
  { countryCode: "SD", countryName: "SUDAN" },
  { countryCode: "SR", countryName: "SURINAME" },
  { countryCode: "SJ", countryName: "SVALBARD AND JAN MAYEN" },
  { countryCode: "SZ", countryName: "SWAZILAND" },
  { countryCode: "SE", countryName: "SWEDEN" },
  { countryCode: "CH", countryName: "SWITZERLAND" },
  { countryCode: "SY", countryName: "SYRIAN ARAB REPUBLIC" },
  { countryCode: "TW", countryName: "TAIWAN, PROVINCE OF CHINA" },
  { countryCode: "TJ", countryName: "TAJIKISTAN" },
  { countryCode: "TZ", countryName: "TANZANIA, UNITED REPUBLIC OF" },
  { countryCode: "TH", countryName: "THAILAND" },
  { countryCode: "TG", countryName: "TOGO" },
  { countryCode: "TK", countryName: "TOKELAU" },
  { countryCode: "TO", countryName: "TONGA" },
  { countryCode: "TT", countryName: "TRINIDAD AND TOBAGO" },
  { countryCode: "TN", countryName: "TUNISIA" },
  { countryCode: "TR", countryName: "TURKEY" },
  { countryCode: "TM", countryName: "TURKMENISTAN" },
  { countryCode: "TC", countryName: "TURKS AND CAICOS ISLANDS" },
  { countryCode: "TV", countryName: "TUVALU" },
  { countryCode: "UG", countryName: "UGANDA" },
  { countryCode: "UA", countryName: "UKRAINE" },
  { countryCode: "AE", countryName: "UNITED ARAB EMIRATES" },
  { countryCode: "GB", countryName: "UNITED KINGDOM" },
  { countryCode: "US", countryName: "UNITED STATES" },
  { countryCode: "UM", countryName: "UNITED STATES MINOR OUTLYING ISLANDS" },
  { countryCode: "UY", countryName: "URUGUAY" },
  { countryCode: "UZ", countryName: "UZBEKISTAN" },
  { countryCode: "VU", countryName: "VANUATU" },
  { countryCode: "VE", countryName: "VENEZUELA" },
  { countryCode: "VN", countryName: "VIET NAM" },
  { countryCode: "VG", countryName: "VIRGIN ISLANDS, BRITISH" },
  { countryCode: "VI", countryName: "VIRGIN ISLANDS, U.S." },
  { countryCode: "WF", countryName: "WALLIS AND FUTUNA" },
  { countryCode: "EH", countryName: "WESTERN SAHARA" },
  { countryCode: "YE", countryName: "YEMEN" },
  { countryCode: "YU", countryName: "YUGOSLAVIA" },
  { countryCode: "ZM", countryName: "ZAMBIA" },
  { countryCode: "ZW", countryName: "ZIMBABWE" },
];

export default countryList;
